### ISSUE TITLE
handle content type for svg image

### ISSUE THREAD

**Issue by herbertwang-me** [mijia/gobuildweb#9]
Dear @mijia 
We'd like to use an open-source plugin which will use svg as icon type(using backgroup image in its css file), but the browser cannot render correctly, since that the content type of the svg is "text/xml" as response. Is there a way to add the MIME Type mapping for svg?  
Thanks in advance!

**Comment by mijia** [comment]
@nanquan Hi, I think we can do either of each way like 1) using the nginx as the reverse proxy and add the mimetype in the nginx config, using the Go server serving the static files, 2) like in our web package github.com/mijia/sweb, we add a function called FilesWithHook and changing the MIME type in the handler hook as in the code https://github.com/mijia/sweb/blob/master/server/routes.go#L92

We didn't have enough time to dig into this, but the FileHook stuff worked for us in such situation. Please let me know if you have further question. :)

**Comment by herbertwang-me** [comment]
@mijia thanks a lot for your replay 
Yes, we have the similar solution with option 1 you mentioned, but it's not a 'perfect' way to resolve this issue. We will try to use the second way to fix it.
Thanks again for your supports :+1:
